{% set name = "ustrid" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ustrid-{{ version }}.tar.gz
  sha256: c8d7176e998381a605cba6a3d82978888c604f10011542767a44eed527b551b3

build:
  entry_points:
    - ustrid = ustrid.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.5

test:
  imports:
    - ustrid
  commands:
    - pip check
    - ustrid --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/ustrid
  summary: Uniquely generated string identifiers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
