{% set name = "ustrid" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ustrid-{{ version }}.tar.gz
  sha256: efa96dbccb424dd274a7bafe65afe00032410b73d9435de4bddd45ec61e65998

build:
  entry_points:
    - ustrid = ustrid.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ustrid
  commands:
    - pip check
    - ustrid --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/ustrid
  summary: Uniquely generated string identifiers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
